@BattleshipPirateAdventure.WebApi_HostAddress = http://localhost:5033

###

POST {{BattleshipPirateAdventure.WebApi_HostAddress}}/game/Player1InitField
Accept: application/json
Content-Type: application/json

{
  "id": "99",
  "ships": [
    {
      "name": "skipper",
      "size": 1,
      "headLocation": {
        "row": 1,
        "column": 1
      },
      "orientation": 1
    }
  ]
}

###
