@server = http://localhost:7035
@game-id = 949b32e7-2321-430c-a4e4-17f236c2eb0a

###

POST {{server}}/game/create
Accept: application/json
Content-Type: application/json

{
  "player1": "valdis"
}

###

POST {{server}}/game/{{game-id}}/join
Accept: application/json
Content-Type: application/json

{
  "player2": "gustavs"
}

###

POST {{server}}/game/{{game-id}}/init-field
Accept: application/json
Content-Type: application/json

{
  "player1": "valdis",
  "ships": [
    {
      "name": "First ship",
      "size": 3,
      "headLocation": {
        "row": 2,
        "column": 3
      },
      "orientation": 1
    }
  ]
}
