//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module BattleshipPirateAdventure.WebApi.Features.Shared.Models {
	export interface IResource
	{
		Links: any[];
	}
}
module BattleshipPirateAdventure.WebApi.Features.Root.Models {
	export interface IRootResponseDto extends BattleshipPirateAdventure.WebApi.Features.Shared.Models.IResource
	{
	}
}
module BattleshipPirateAdventure.WebApi.Features.Game.Models {
	export interface ICreateGameRequestDto
	{
		Player1: string;
	}
	export interface ICreateGameResponseDto extends BattleshipPirateAdventure.WebApi.Features.Shared.Models.IResource
	{
		Id: string;
		Size: any;
		State: number;
	}
	export interface IGameDto
	{
		Id: any;
		ColumnSize: number;
		RowSize: number;
		Player1: BattleshipPirateAdventure.WebApi.Features.Game.Models.IGamePlayerDto;
		Player2: BattleshipPirateAdventure.WebApi.Features.Game.Models.IGamePlayerDto;
		State: number;
	}
	export interface IGamePlayerDto
	{
		Id: string;
		PlayerType: number;
		State: number;
	}
	export interface IJoinGameRequestDto
	{
		Player2: string;
	}
	export interface IJoinGameResponseDto extends BattleshipPirateAdventure.WebApi.Features.Shared.Models.IResource
	{
		GameId: any;
	}
}
